import { index, rootRoute, route } from '@tanstack/virtual-file-routes';

// Every address of the screens, once: files are named in English, addresses read in French
// (doctrine ARCHITECTURE_APP §3). The space first, then the Administration (spec 010).
export const routes = rootRoute('__root.tsx', [
  index('index.tsx'),
  route('/a-faire', 'inbox.tsx'),
  route('/notifications', 'notifications.tsx'),
  route('/recherche', 'search.tsx'),
  route('/assistant', 'assistant.tsx'),
  route('/assistant/connexion', 'ai-connection.tsx'),
  route('/assistant/taches', 'schedules.tsx'),
  route('/assistant/memoire', 'memory.tsx'),
  route('/mes-agents', 'my-agents.tsx'),
  route('/ressources', 'resources.tsx'),
  route('/bibliotheque', 'library.tsx'),
  route('/ressources/demandes', 'app-requests.tsx'),
  route('/ressources/demandes/nouvelle', 'app-request-new.tsx'),
  route('/ressources/demandes/$requestId', 'app-request.tsx'),
  route('/enquetes', 'surveys.tsx'),
  route('/enquetes/campagnes/nouvelle', 'survey-campaign-new.tsx'),
  route('/enquetes/questionnaires/$questionnaireId', 'questionnaire-edit.tsx'),
  route('/enquetes/$campaignId', 'survey-campaign.tsx'),
  route('/enquetes/repondre/$respondentId', 'survey-answer.tsx'),
  route('/performance', 'performance.tsx'),
  route('/performance/$quarterId', 'performance-quarter.tsx'),
  route('/performance/revues/$reviewId', 'review.tsx'),
  route('/performance/revues/$reviewId/mesures', 'review-measures.tsx'),
  route('/performance/revues/$reviewId/bilan', 'review-record.tsx'),
  route('/mon-equipe', 'team.tsx'),
  route('/instances', 'meetings.tsx'),
  route('/instances/$meetingId', 'meeting.tsx'),
  route('/actions', 'actions.tsx'),
  route('/conformite', 'compliance.tsx'),
  route('/administration', 'admin-home.tsx'),
  route('/administration/organisation', 'structure.tsx'),
  route('/administration/personnes', 'people.tsx'),
  route('/administration/personnes/importer', 'people-import.tsx'),
  route('/administration/droits', 'rights.tsx'),
  route('/administration/modules', 'modules.tsx'),
  route('/administration/circuits', 'circuits.tsx'),
  route('/administration/registre', 'registry.tsx'),
  route('/administration/agents', 'agents.tsx'),
  route('/administration/boite-de-test', 'outbox.tsx'),
  route('/administration/ia', 'admin-ai.tsx'),
  route('/administration/bibliotheque', 'admin-library.tsx'),
  route('/administration/demo', 'demo.tsx'),
  route('/lien/$token', 'link.tsx'),
  route('/auth/connexion', 'auth/sign-in.ts'),
  route('/auth/callback', 'auth/callback.ts'),
  route('/auth/sortie', 'auth/sign-out.ts'),
  route('/health', 'api/health.ts'),
  route('/assistant/flux', 'api/assistant-stream.ts'),
]);
